version: 2
jobs:
  dog:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm run dog
  cat:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm run cat

workflows:
  version: 2
  dog_workflow:
    jobs:
      - dog
  cat_workflow:
    triggers:
      - schedule:
          cron: "0,5,10,15,20,25,30,35,40,45,50,55 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - cat
