version: 2
jobs:
  dog:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm run dog
  cat:
    docker:
      - image: node:8
    steps:
      - checkout
      - run: npm run cat

workflows:
  version: 2
  cat_workflow:
    triggers:
      - schedule:
          cron: "30 9 * * *"
    jobs:
      - cat
